name: 'Install Godot'
description: 'Installs the Godot engine for macOS'

inputs:
  godot-version:
    description: 'The version of Godot to build with'
    required: true
    default: 0.0
  install-templates:
    description: 'Whether or not to install the Godot export templates'
    required: false
    default: false

outputs:
  godot-executable:
    description: 'The installed executable location'
    value: ${{ steps.assign-executable.outputs.GODOT_EXECUTABLE }}

runs:
  using: 'composite'
  steps:
    - name: Install Godot
      shell: bash
      run: |
        curl -o ./godot.zip "https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_macos.universal.zip"
        unzip ./godot.zip
        mv ./Godot.app /Applications/Godot.app

    - name: Install Godot templates
      if: ${{ inputs.install-templates }}
      shell: bash
      env:
        GODOT_TEMPLATES_DIR: /Users/runner/Library/Application Support/Godot/export_templates
      run: |
        curl -o ./godot-templates.zip "https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz"
        unzip ./godot-templates.zip
        mkdir -p "$GODOT_TEMPLATES_DIR"
        mv ./templates "$GODOT_TEMPLATES_DIR/${{ inputs.godot-version }}.stable"

    - name: Report back the executable location
      shell: bash
      env:
        GODOT_EXECUTABLE: /Applications/Godot.app/Contents/MacOS/Godot
      run: echo "GODOT_EXECUTABLE=${{ env.GODOT_EXECUTABLE }}" >> $GITHUB_OUTPUT
      id: assign-executable
